# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=no]
  - repo: https://github.com/bdegreve/bramz-pre-commit-hooks.git
    rev: 91ed690857473b83ae03feb0b12f34b824f625a1
    hooks:
      - id: bramz-fix-copyright
        args: [--author=Bram de Greve]
        exclude: '^conanfile\.py$'
      - id: bramz-check-conan-requires
